### ISSUE TITLE
Server does not start on 1.0.7: NoClassDefFoundError: com/terraformersmc/modmenu/api/ModMenuApi

### ISSUE THREAD

**Issue by Akzyra** [JamCoreModding/JamLib#5]
I use `rightclickharvest-fabric-4.1.4+1.20.4.jar` and 
when I updated to `jamlib-fabric-1.0.7+1.20.4.jar` 
the server does not start with attached log output.

When I revert back to 1.0.6 the server starts normally. 
Is Mod Menu needed on the server now?

Log:

```
minecraft-private  | [20:14:06] [main/ERROR]: Failed to start the minecraft server
minecraft-private  | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'rightclickharvest'!
minecraft-private  |    at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
minecraft-private  | Caused by: java.lang.NoClassDefFoundError: com/terraformersmc/modmenu/api/ModMenuApi
minecraft-private  |    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
minecraft-private  |    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
minecraft-private  |    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft-private  |    at java.lang.Class.forName0(Native Method) ~[?:?]
minecraft-private  |    at java.lang.Class.forName(Unknown Source) ~[?:?]
minecraft-private  |    at io.github.jamalam360.jamlib.config.ConfigManager.tryNotifyModMenuCompatibilityOfNewConfigManager(ConfigManager.java:79) ~[jamlib-fabric-1.0.7+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.jamlib.config.ConfigManager.<init>(ConfigManager.java:73) ~[jamlib-fabric-1.0.7+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.jamlib.config.ConfigManager.<init>(ConfigManager.java:46) ~[jamlib-fabric-1.0.7+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.rightclickharvest.RightClickHarvest.<clinit>(RightClickHarvest.java:34) ~[rightclickharvest-fabric-4.1.4+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.rightclickharvest.fabriclike.RightClickHarvestFabricLike.init(RightClickHarvestFabricLike.java:7) ~[rightclickharvest-fabric-4.1.4+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.rightclickharvest.fabric.RightClickHarvestFabric.onInitialize(RightClickHarvestFabric.java:10) ~[rightclickharvest-fabric-4.1.4+1.20.4.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    ... 7 more
minecraft-private  | Caused by: java.lang.ClassNotFoundException: com.terraformersmc.modmenu.api.ModMenuApi
minecraft-private  |    at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft-private  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft-private  |    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
minecraft-private  |    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
minecraft-private  |    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft-private  |    at java.lang.Class.forName0(Native Method) ~[?:?]
minecraft-private  |    at java.lang.Class.forName(Unknown Source) ~[?:?]
minecraft-private  |    at io.github.jamalam360.jamlib.config.ConfigManager.tryNotifyModMenuCompatibilityOfNewConfigManager(ConfigManager.java:79) ~[jamlib-fabric-1.0.7+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.jamlib.config.ConfigManager.<init>(ConfigManager.java:73) ~[jamlib-fabric-1.0.7+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.jamlib.config.ConfigManager.<init>(ConfigManager.java:46) ~[jamlib-fabric-1.0.7+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.rightclickharvest.RightClickHarvest.<clinit>(RightClickHarvest.java:34) ~[rightclickharvest-fabric-4.1.4+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.rightclickharvest.fabriclike.RightClickHarvestFabricLike.init(RightClickHarvestFabricLike.java:7) ~[rightclickharvest-fabric-4.1.4+1.20.4.jar:?]
minecraft-private  |    at io.github.jamalam360.rightclickharvest.fabric.RightClickHarvestFabric.onInitialize(RightClickHarvestFabric.java:10) ~[rightclickharvest-fabric-4.1.4+1.20.4.jar:?]
minecraft-private  |    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
minecraft-private  |    ... 7 more
```

**Comment by Jamalam360** [comment]
Ah, that's an error in the update yes. Will release a fix shortly, thanks for reporting
